---
- name: Playbook to install Nginx module
  hosts: ec2
  become: yes
  
  #install nginx module
  tasks:
  - name: Install Nginx module
    apt:
     name: nginx
     state: latest
     
  #start nginx module using service module
  - name: Start nginx, if not running
    service:
     name: nginx
     state: started
...
